name: "PHPUnit"
#path: "{{ config('tddd.root.code.path') }}/pragmarx/tddd"
# Set in config/tddd/root.yml
path: "{{ config('tddd.root.code.path') }}"
watch_folders:
  - app
  - tests
exclude: []
depends: []
tests_path: tests
suites:
#  feature:
#    tester: phpunit
#    tests_path: Feature
#    command_options: ''
#    file_mask: "*Test.php"
#    retries: 0
  unit:
    tester: phpunit
    tests_path: UnitTests
    command_options: ''
    file_mask: "*Test.php"
    retries: 0
